### ISSUE TITLE
Using with nodemon?

### ISSUE THREAD

**Issue by mkvlrn-cm42** [enquirer/enquirer-prompt-radio#2]
It's probably an issue with the way nodemon does things, but when starting an app with it, the prompt is not exactly responsive to the arrow keys, and instead I get the "raw" commands the keyboard sends to the computer:

![image](https://user-images.githubusercontent.com/6718750/31055327-93a507e8-a697-11e7-8670-ffc34b1790e0.png)

I'm using ZSH, but I believe the problem is in the way nodemon calls the script. And I understand if it was an actual bug I should submit an issue over there, but it's more a nuisance than anything, and perhaps someone using this may have found a solution.

Thanks!

**Comment by doowb** [comment]
Thanks for bringing this up. I'm thinking it probably is an issue with `nodemon` but if `nodemon` is starting the script as a child process, which might be a common scenario with other systems, then we might be able to detect it and handle it. I'm not sure how that would work, but if someone does find a solution, it would be awesome to do a PR to [readline-ui](https://github.com/enquirer/readline-ui) or [readline-utils](https://github.com/enquirer/readline-utils) depending on where it fits.

**Comment by doowb** [comment]
Closing as this prompt has been completely refactored from the ground up, and is now included in [Enquirer 2.0](https://github.com/enquirer/enquirer). Please direct all questions, issues and feature requests to that repository.
